INSERT INTO questions ( question, category, ans1, ans2, ans3, ans4, ans5)
VALUES  ("The unborn child has a fundamental individual right to life which cannot be infringed", Social Issues, null,null,null,null,null),
		("Same sex marriage should not be accepted by society", Social Issues, null,null,null,null,null),
		("Abortion is a woman’s unrestricted right", Social Issues, null,null,null,null,null),
		("Education is best provided by the free market, achieving greater quality, accountability and efficiency with more diversity of School Choice", Social Issues, ,null,null,null,null,null),
		("Institutional racism is the main reason why many minorities can't get ahead these days", Social Issues,null,null,null,null,null),
        ("The best way to ensure peace is through military strength", International Issues, null,null,null,null,null),
        ("No funds be appropriated for any kind of foreign aid program" International Issues, null,null,null,null,null),
        ("Government to sign the International Criminal Courtagreement and respect the authority of that institution", International Issues,  null,null,null,null,null),
        ("Belief that free trade engenders positive international relationships", International Issues,  null,null,null,null,null),
        ("Good diplomacy is the best way to ensure peace",  International Issues,  null,null,null,null,null),
        ("Free market system is the best solution to providing the greatest possible care to the most amount of Americans", Domestic Issues,  null,null,null,null,null),
        ("The government must not spend more than it takes in during the payoff period", Domestic Issues,  null,null,null,null,null),
        ("The Internet is a commons, developed with public funds, and must insure freedom and equality of access", Domestic Issues,  null,null,null,null,null),
        ("Oppose all government intervention and regulation on Wages, Prices, Profits, Production and Interest rates",  Domestic Issues,  null,null,null,null,null),
        ("Health care is a right, not a privilege, and our health care system should put people before profits",Domestic Issues, null,null,null,null,null),
        ("Creating a low tax environment for job creators is the best way to stimulate growth.", Economic Issues, null,null,null,null,null),
        ("Congress shall not levy taxes on personal incomes, estates, and/or gifts", Economic Issues, null,null,null,null,null),
        ("Government regulation of business is necessary to protect the public interest.",Economic Issues, null,null,null,null,null),
        ("The only role of government in the economy is to protect property rights, adjudicate disputes, and provide a legal framework in which voluntary trade is protected",Economic Issues, null,null,null,null,null), 
		("The wealthiest Americans and largest corporations must pay their fair share of taxes",Economic Issues, null,null,null,null,null),
